service: express

frameworkVersion: '2'

plugins:
  - serverless-offline #serverless-offline needs to be last in the list

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: src/handlers/customer.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
