service: serverless-express

frameworkVersion: '2'

plugins:
  - serverless-offline #serverless-offline needs to be last in the list

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  apiGateway:
    metrics: true
  logs:
    restApi: true
  environment:
    FOO: ${env:FOO}
    BAZ: ${env:BAZ}

functions:
  customer:
    handler: src/handlers/customer/index.handler
    events:
      - http:
          path: /customers
          method: GET
      - http:
          path: /customers/{id}
          method: GET
          request:
            parameters:
              paths:
                id: true
      - http:
          path: /customers
          method: POST
      - http:
          path: /customers/{id}
          method: DELETE
          request:
            parameters:
              paths:
                id: true
  widget:
    handler: src/handlers/widget/index.handler
    events:
      - http:
          path: /widgets
          method: GET